version: '3.8'

services:
  bus:
    image: jrgiadach/soabus:v1
    container_name: soabus
    ports:
      - "5000:5000"
  service:
    build: ./service
    container_name: service
  client:
    build: ./client
    container_name: client
