version: "3.9"
services:
  bus_service:
    image: jrgiadach/soabus:v1
    container_name: soabus
    ports:
      - "5000:5000"
  product_service:
    build: ./services/product_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=product
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=arqui_db
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      - bus_service
  location_service:
    build: ./services/location_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=SEV02
    depends_on:
      - bus_service
  optimization_service:
    build: ./services/optimization_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=optimiz
    depends_on:
      - bus_service
  movement_service:
    build: ./services/movement_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=movement
    depends_on:
      - bus_service
  visualization_service:
    build: ./services/visualization_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=visualiz
    depends_on:
      - bus_service
  alert_report_service:
    build: ./services/alert_report_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=alertrep
    depends_on:
      - bus_service
  order_service:
    build: ./services/order_service
    environment:
      - BUS_HOST=bus_service
      - BUS_PORT=5000
      - SERVICE_NAME=order
    depends_on:
      - bus_service
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=arqui_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  pgdata: